# Generated by Django 2.2 on 2022-03-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptosystem',
            name='desc',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='cryptosystem',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
