# Generated by Django 2.2 on 2022-04-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0002_auto_20220328_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptosystem',
            name='icon',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
