# Generated by Django 2.2 on 2022-04-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0007_auto_20220403_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptosystem',
            name='icon',
            field=models.ImageField(default='/staticfiles/assets/default.jpg', upload_to=''),
        ),
    ]
