# Generated by Django 2.2 on 2022-04-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0008_auto_20220403_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptosystem',
            name='icon',
            field=models.ImageField(default='/staticfiles/assets/default.jpg', upload_to='media/'),
        ),
    ]
