# Generated by Django 2.2 on 2022-04-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0009_auto_20220403_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSAInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeP', models.IntegerField()),
                ('primeQ', models.IntegerField()),
                ('clearText', models.CharField(max_length=1024)),
                ('cipherText', models.CharField(max_length=1024)),
            ],
        ),
    ]
