# Generated by Django 2.2 on 2022-04-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0010_rsainput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsainput',
            name='cipherText',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='rsainput',
            name='clearText',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
