# Generated by Django 2.2 on 2022-04-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0011_auto_20220406_1441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RSAInput',
        ),
    ]
