# Generated by Django 2.2 on 2022-04-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0012_delete_rsainput'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSAInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeP', models.IntegerField()),
                ('primeQ', models.IntegerField()),
                ('clearText', models.CharField(blank=True, max_length=1200)),
                ('cipherText', models.CharField(blank=True, max_length=1200)),
            ],
        ),
    ]
