# Generated by Django 2.2 on 2022-04-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0013_rsainput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsainput',
            name='primeP',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rsainput',
            name='primeQ',
            field=models.BigIntegerField(),
        ),
    ]
