# Generated by Django 2.2 on 2022-04-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0014_auto_20220407_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsainput',
            name='primeP',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rsainput',
            name='primeQ',
            field=models.BigIntegerField(blank=True),
        ),
    ]
