# Generated by Django 2.2 on 2022-04-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0016_rabininput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rabininput',
            name='publicKey',
        ),
        migrations.AlterField(
            model_name='cryptosystem',
            name='icon',
            field=models.ImageField(default='/staticfiles/assets/default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='rabininput',
            name='primeP',
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AlterField(
            model_name='rabininput',
            name='primeQ',
            field=models.CharField(blank=True, max_length=1200),
        ),
    ]
