# Generated by Django 2.2 on 2022-04-09 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0017_auto_20220408_1942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RabinInput',
        ),
    ]
