# Generated by Django 2.2 on 2022-04-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0018_delete_rabininput'),
    ]

    operations = [
        migrations.CreateModel(
            name='RabinInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeP', models.DecimalField(decimal_places=0, max_digits=78)),
                ('primeQ', models.DecimalField(decimal_places=0, max_digits=78)),
                ('clearText', models.CharField(blank=True, max_length=1200)),
                ('cipherText', models.CharField(blank=True, max_length=1200)),
            ],
        ),
        migrations.AlterField(
            model_name='rsainput',
            name='primeP',
            field=models.DecimalField(decimal_places=0, max_digits=78),
        ),
        migrations.AlterField(
            model_name='rsainput',
            name='primeQ',
            field=models.DecimalField(decimal_places=0, max_digits=78),
        ),
    ]
