# Generated by Django 2.2 on 2022-04-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0019_auto_20220408_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabininput',
            name='clearText',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
