# Generated by Django 2.2 on 2022-04-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0020_auto_20220408_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabininput',
            name='cipherText',
            field=models.CharField(blank=True, max_length=65536),
        ),
        migrations.AlterField(
            model_name='rabininput',
            name='clearText',
            field=models.CharField(blank=True, max_length=65536),
        ),
        migrations.AlterField(
            model_name='rsainput',
            name='cipherText',
            field=models.CharField(blank=True, max_length=65536),
        ),
        migrations.AlterField(
            model_name='rsainput',
            name='clearText',
            field=models.CharField(blank=True, max_length=65536),
        ),
    ]
