# Generated by Django 2.2 on 2022-04-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0021_auto_20220408_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='MVInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearText', models.CharField(blank=True, max_length=65536)),
                ('cipherText', models.CharField(blank=True, max_length=65536)),
            ],
        ),
    ]
