# Generated by Django 2.2 on 2022-04-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0022_mvinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='mvinput',
            name='keyParam',
            field=models.CharField(blank=True, max_length=65536),
        ),
    ]
