# Generated by Django 2.2 on 2022-04-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0023_mvinput_keyparam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvinput',
            name='keyParam',
            field=models.CharField(max_length=65536),
        ),
    ]
