# Generated by Django 2.2 on 2022-04-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0024_auto_20220415_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='GammalInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pNumber', models.DecimalField(decimal_places=0, max_digits=512)),
                ('qNumber', models.DecimalField(decimal_places=0, max_digits=512)),
                ('gNumber', models.DecimalField(decimal_places=0, max_digits=512)),
                ('clearText', models.CharField(blank=True, max_length=65536)),
                ('cipherText', models.CharField(blank=True, max_length=65536)),
            ],
        ),
    ]
