# Generated by Django 2.2 on 2022-04-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0025_gammalinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='gammalinput',
            name='privKey',
            field=models.CharField(blank=True, default='-', max_length=65536),
        ),
        migrations.AddField(
            model_name='gammalinput',
            name='pubKey',
            field=models.CharField(blank=True, default='-', max_length=65536),
        ),
        migrations.AlterField(
            model_name='rabininput',
            name='primeP',
            field=models.DecimalField(decimal_places=0, max_digits=128),
        ),
        migrations.AlterField(
            model_name='rabininput',
            name='primeQ',
            field=models.DecimalField(decimal_places=0, max_digits=128),
        ),
    ]
