# Generated by Django 2.2 on 2022-04-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0026_auto_20220417_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gammalinput',
            name='gNumber',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=512),
        ),
        migrations.AlterField(
            model_name='gammalinput',
            name='pNumber',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=512),
        ),
        migrations.AlterField(
            model_name='gammalinput',
            name='qNumber',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=512),
        ),
        migrations.AlterField(
            model_name='mvinput',
            name='keyParam',
            field=models.CharField(blank=True, max_length=65536),
        ),
        migrations.AlterField(
            model_name='rabininput',
            name='primeP',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=128),
        ),
        migrations.AlterField(
            model_name='rabininput',
            name='primeQ',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=128),
        ),
        migrations.AlterField(
            model_name='rsainput',
            name='primeP',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=78),
        ),
        migrations.AlterField(
            model_name='rsainput',
            name='primeQ',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=78),
        ),
    ]
