# Generated by Django 2.2 on 2022-04-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0027_auto_20220417_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsainput',
            name='primeP',
            field=models.CharField(blank=True, max_length=65536),
        ),
        migrations.AlterField(
            model_name='rsainput',
            name='primeQ',
            field=models.CharField(blank=True, max_length=65536),
        ),
    ]
