# Generated by Django 3.2.9 on 2022-04-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0028_auto_20220417_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gammalinput',
            name='gNumber',
        ),
        migrations.RemoveField(
            model_name='gammalinput',
            name='pNumber',
        ),
        migrations.RemoveField(
            model_name='gammalinput',
            name='qNumber',
        ),
        migrations.RemoveField(
            model_name='mvinput',
            name='keyParam',
        ),
        migrations.AddField(
            model_name='mvinput',
            name='privKey',
            field=models.CharField(blank=True, default='-', max_length=65536),
        ),
        migrations.AddField(
            model_name='mvinput',
            name='pubKey',
            field=models.CharField(blank=True, default='-', max_length=65536),
        ),
    ]
