# Generated by Django 3.2.9 on 2022-04-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0029_auto_20220419_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabininput',
            name='primeP',
            field=models.CharField(blank=True, max_length=65536),
        ),
        migrations.AlterField(
            model_name='rabininput',
            name='primeQ',
            field=models.CharField(blank=True, max_length=65536),
        ),
    ]
