# Generated by Django 2.2 on 2022-05-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0030_auto_20220419_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gammalinput',
            name='cipherText',
            field=models.CharField(blank=True, max_length=4294967296),
        ),
        migrations.AlterField(
            model_name='gammalinput',
            name='clearText',
            field=models.CharField(blank=True, max_length=4294967296),
        ),
        migrations.AlterField(
            model_name='gammalinput',
            name='privKey',
            field=models.CharField(blank=True, default='-', max_length=4294967296),
        ),
        migrations.AlterField(
            model_name='gammalinput',
            name='pubKey',
            field=models.CharField(blank=True, default='-', max_length=4294967296),
        ),
        migrations.AlterField(
            model_name='mvinput',
            name='cipherText',
            field=models.CharField(blank=True, max_length=4294967296),
        ),
        migrations.AlterField(
            model_name='mvinput',
            name='clearText',
            field=models.CharField(blank=True, max_length=4294967296),
        ),
        migrations.AlterField(
            model_name='mvinput',
            name='privKey',
            field=models.CharField(blank=True, default='-', max_length=4294967296),
        ),
        migrations.AlterField(
            model_name='mvinput',
            name='pubKey',
            field=models.CharField(blank=True, default='-', max_length=4294967296),
        ),
        migrations.AlterField(
            model_name='rabininput',
            name='cipherText',
            field=models.CharField(blank=True, max_length=4294967296),
        ),
        migrations.AlterField(
            model_name='rabininput',
            name='clearText',
            field=models.CharField(blank=True, max_length=4294967296),
        ),
        migrations.AlterField(
            model_name='rabininput',
            name='primeP',
            field=models.CharField(blank=True, max_length=4294967296),
        ),
        migrations.AlterField(
            model_name='rabininput',
            name='primeQ',
            field=models.CharField(blank=True, max_length=4294967296),
        ),
        migrations.AlterField(
            model_name='rsainput',
            name='cipherText',
            field=models.CharField(blank=True, max_length=4294967296),
        ),
        migrations.AlterField(
            model_name='rsainput',
            name='clearText',
            field=models.CharField(blank=True, max_length=4294967296),
        ),
        migrations.AlterField(
            model_name='rsainput',
            name='primeP',
            field=models.CharField(blank=True, max_length=4294967296),
        ),
        migrations.AlterField(
            model_name='rsainput',
            name='primeQ',
            field=models.CharField(blank=True, max_length=4294967296),
        ),
    ]
