# Generated by Django 2.2 on 2022-05-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0031_auto_20220504_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSADSSInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeP', models.CharField(blank=True, max_length=4294967296)),
                ('primeQ', models.CharField(blank=True, max_length=4294967296)),
                ('message', models.CharField(blank=True, max_length=4294967296)),
                ('signature', models.CharField(blank=True, max_length=4294967296)),
            ],
        ),
    ]
