# Generated by Django 2.2 on 2022-05-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0032_rsadssinput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsadssinput',
            name='message',
        ),
        migrations.RemoveField(
            model_name='rsadssinput',
            name='signature',
        ),
        migrations.AddField(
            model_name='rsadssinput',
            name='cipherText',
            field=models.CharField(blank=True, max_length=4294967296),
        ),
        migrations.AddField(
            model_name='rsadssinput',
            name='clearText',
            field=models.CharField(blank=True, max_length=4294967296),
        ),
    ]
