# Generated by Django 2.2 on 2022-05-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0033_auto_20220518_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsadssinput',
            old_name='cipherText',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='rsadssinput',
            old_name='clearText',
            new_name='signature',
        ),
    ]
