# Generated by Django 2.2 on 2022-05-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0034_auto_20220518_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='GammalDSSInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubKey', models.CharField(blank=True, default='-', max_length=4294967296)),
                ('privKey', models.CharField(blank=True, default='-', max_length=4294967296)),
                ('message', models.CharField(blank=True, max_length=4294967296)),
                ('signature', models.CharField(blank=True, max_length=4294967296)),
            ],
        ),
    ]
