# Generated by Django 2.2 on 2022-06-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0035_gammaldssinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEncryptionInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
