# Generated by Django 2.2 on 2022-06-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0036_imageencryptioninput'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageencryptioninput',
            old_name='image',
            new_name='clearImage',
        ),
    ]
