# Generated by Django 2.2 on 2022-06-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0037_auto_20220604_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageencryptioninput',
            name='caption',
        ),
    ]
