# Generated by Django 2.2 on 2022-06-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0038_remove_imageencryptioninput_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageencryptioninput',
            name='clearImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
