# Generated by Django 2.2 on 2022-06-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0039_auto_20220604_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageencryptioninput',
            name='clearImage',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
