# Generated by Django 2.2 on 2022-06-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0044_auto_20220607_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsadssinput',
            name='clearFile',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='rsadssinput',
            name='message',
            field=models.CharField(blank=True, max_length=4294967296),
        ),
    ]
