# Generated by Django 2.2 on 2022-06-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0046_auto_20220607_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageencryptioninput',
            name='cipherImageT1',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='imageencryptioninput',
            name='cipherImageT2',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
