# Generated by Django 2.2 on 2022-06-25 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0048_block_blockchain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='-', max_length=4294967296)),
                ('receiver', models.CharField(default='-', max_length=4294967296)),
            ],
        ),
        migrations.DeleteModel(
            name='Blockchain',
        ),
        migrations.AddField(
            model_name='block',
            name='hash',
            field=models.CharField(default='-', max_length=4294967296),
        ),
        migrations.AddField(
            model_name='transaction',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptogyapp.Block'),
        ),
    ]
