# Generated by Django 2.2 on 2022-06-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0050_auto_20220625_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='numoftransactions',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
