# Generated by Django 2.2 on 2022-06-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0051_block_numoftransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='numoftransactions',
            field=models.IntegerField(default=5),
        ),
    ]
