# Generated by Django 2.2 on 2022-06-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0052_auto_20220627_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='numoftransactions',
            field=models.IntegerField(default=0),
        ),
    ]
