# Generated by Django 2.2 on 2022-06-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptogyapp', '0053_auto_20220627_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.CharField(default='-', max_length=4294967296),
        ),
    ]
